### ISSUE TITLE
Documentation: Releases Tag not updated with latest

### ISSUE THREAD

**Issue by Deric4** [lingua-pupuli/docs#13]
I'm not sure how the *Releases* tab on the website is updated but it looks like its missing the 0.21.0 release changelog info:

![Screen Shot 2019-09-30 at 11 24 18 AM](https://user-images.githubusercontent.com/5762138/65897649-5c41b680-e375-11e9-91a8-3ad442568c1c.png)

**Comment by jpogran** [comment]
Thanks @Deric4, this is a manual process at the moment and we just released 0.21.0 3 days ago and haven't gotten around to it. I'll get on this today

**Comment by jpogran** [comment]
This was resolved in #15 . Thanks for the issue!
